// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner.vue')['default']
    Button: typeof import('./components/button.vue')['default']
    DepsIcon: typeof import('./components/depsIcon.vue')['default']
    Home: typeof import('./components/home.vue')['default']
    HomeSponsors: typeof import('./components/HomeSponsors.vue')['default']
    HomeSponsorsGroup: typeof import('./components/HomeSponsorsGroup.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    PiniaLogo: typeof import('./components/PiniaLogo.vue')['default']
    TheExperience: typeof import('./components/portal-journey/TheExperience.vue')['default']
    TheFireFlies: typeof import('./components/portal-journey/TheFireFlies.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    ThePortal: typeof import('./components/portal-journey/ThePortal.vue')['default']
    VueMasteryHomeLink: typeof import('./components/VueMasteryHomeLink.vue')['default']
    VueMasteryLogoLink: typeof import('./components/VueMasteryLogoLink.vue')['default']
    VueSchoolLink: typeof import('./components/VueSchoolLink.vue')['default']
  }
}
